[build]
# Default build configurations
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true

